apiVersion: v2
name: northscope
description: Read-only Kubernetes north-south traffic topology debugger
type: application
kubeVersion: ">=1.30.0-0"
version: 0.1.5
appVersion: "0.1.5"
keywords:
  - kubernetes
  - ingress
  - topology
  - debugging
  - observability
home: https://github.com/emircanagac/northscope
sources:
  - https://github.com/emircanagac/northscope
maintainers:
  - name: Emircan Agac
